# Generated by Django 5.2.6 on 2026-02-16 00:03

import datetime
import django.db.models.deletion
from django.db import migrations, models

def populate_days(apps, schema_editor):
    # We use apps.get_model to avoid importing the model directly
    Day = apps.get_model('server', 'Day')
    days_to_create = [
        (0, "Monday"), (1, "Tuesday"), (2, "Wednesday"),
        (3, "Thursday"), (4, "Friday"), (5, "Saturday"), (6, "Sunday")
    ]
    for idx, name in days_to_create:
        Day.objects.get_or_create(id=idx)
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(default=datetime.date(1900, 1, 1))),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='No Provider')),
                ('address', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
                ('email', models.TextField(null=True)),
            ],
            options={
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.servicecategory')),
            ],
            options={
                'unique_together': {('type', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('periodic', models.IntegerField(default=0)),
                ('note', models.TextField(default='', null=True)),
                ('audience', models.ManyToManyField(to='server.audience')),
                ('day', models.ManyToManyField(to='server.day')),
                ('provider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.provider')),
                ('type', models.ManyToManyField(to='server.servicetype')),
            ],
            options={
                'unique_together': {('provider', 'start_time', 'end_time', 'periodic', 'note')},
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.date(1900, 1, 1))),
                ('end', models.DateTimeField(default=datetime.date(1900, 1, 1))),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.service')),
            ],
            options={
                'unique_together': {('service_id', 'date')},
            },
        ),
        migrations.RunPython(populate_days),

    ]
