# Generated by Django 5.2.6 on 2025-10-05 18:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('audience', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='No Provider')),
                ('address', models.TextField(null=True)),
                ('phone', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicesCategories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255, unique=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.servicescategories')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.IntegerField(default=0)),
                ('start_time', models.TimeField(default=datetime.time(0, 0))),
                ('end_time', models.TimeField(default=datetime.time(0, 0))),
                ('periodic', models.IntegerField(default=0)),
                ('note', models.TextField(default='')),
                ('audience', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.audience')),
                ('provider', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.providers')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.servicescategories')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='server.servicetype')),
            ],
            options={
                'unique_together': {('provider', 'category', 'type', 'day', 'periodic', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(default=datetime.date(1900, 1, 1))),
                ('end', models.DateTimeField(default=datetime.date(1900, 1, 1))),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.services')),
            ],
            options={
                'unique_together': {('service_id', 'date')},
            },
        ),
    ]
