# Generated by Django 5.2.6 on 2026-02-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(default='No Provider', max_length=255),
        ),
    ]
